### ISSUE TITLE
Multiple Maya instances

### ISSUE THREAD

**Issue by bmumm** [sernst/Nimble#2]
I'm having an issue when there is multiple Maya instances and registered to listen for nimble commands. The python process just locks up and the command seems to only run once for a single Maya.

**Comment by sernst** [comment]
Interesting. Never had that use case before. Nimble was built with hard coded port assignments, which are likely what's causing this problem.

I've committed a change that allows you to override the default ports when desired to handle multiple Maya instances. See the updated README for details.
